"""add candidates table

Revision ID: 3c7ddfb9e73c
Revises: f035a73c21a9
Create Date: 2026-03-29 00:12:13.577687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c7ddfb9e73c'
down_revision: Union[str, Sequence[str], None] = 'f035a73c21a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('constituency_id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituencies.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('constituency_id', 'name', name='uq_candidate_constituency_name')
    )
    op.create_index(op.f('ix_candidates_constituency_id'), 'candidates', ['constituency_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidates_constituency_id'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
